# config.py

WATCHLIST_INDICES = ['NIFTY', 'BANKNIFTY']
WATCHLIST_STOCKS = ['RELIANCE', 'TCS', 'INFY', 'HDFCBANK']

INDEX_OI_EXPIRIES = ['weekly', 'monthly']
STOCK_OI_EXPIRIES = ['3month']

REALTIME_REFRESH_MINUTES = 5